import os
print(os.getcwd())
print(os.getcwd())
print(os.getcwdb())
os.chdir('/media/zahid/Parsonal/TestForPython/')
print(os.getcwd())
print(os.listdir())
os.mkdir('Test')
print(os.listdir())
os.rmdir('Test')
print(os.getcwd())